import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Esqueleto from "@/components/esqueleto";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "PcComponentes",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body className={inter.className}>
                <Esqueleto>
                    <Header />
                    {children}
                    <Footer />
                </Esqueleto>
            </body>
        </html>
    );
}
